#ifndef __GRAVITY_BALL_CONFIG_H__
#define __GRAVITY_BALL_CONFIG_H__

#define PTM_RATIO 20

#define PADDING_LEFT   1
#define PADDING_TOP    5
#define PADDING_RIGTH  12
#define PADDING_BOTTOM 4

#endif // __GRAVITY_BALL_CONFIG_H__
